#+TITLE: CS615 HW1
#+AUTHOR: Hongyi Shen
#+EMAIL: hshen4 AT stevens DOT edu
#+LANGUAGE: en
#+OPTIONS: H:2 num:nil toc:t \n:nil @:t ::t |:t ^:nil f:t *:t TeX:t LaTeX:t skip:nil p:nil
#+STYLE: <link rel="stylesheet" type="text/css" href="worg.css" />
* Setup Environment for EC2 and create an instance
** Configuration AWS CLI tools
   - Due to ec2 tools are already installed under =/opt/ec2tools-1.4=,
     all we need to do is edit bashrc file.
   - Check lab's java version.
     Use ~java -version~ to get java version, make sure it >=1.6. If
     it is not, there is nothing we can do about it.
   - Tell CLI tools where they live
     open ~/.bashrc, add EC2 configuration below to tell the tools who you
     are. The private key and X.509 certification can be retrived
     from Security Credentials page. (The newer version use access key
     and secret key to verify)
	 #+BEGIN_SRC sh
     export EC2_HOME=/opt/ec2tools-1.4
     export PATH=$PATH:$EC2_HOME/bin
     export EC2_PRIVATE_KEY=~/.ec2/pk-XXXXXXXXXXX.cer
     export EC2_CERT=~/.ec2/cert-XXXXXXXXXXXXXXXX.cer
     export JAVA_HOME=/usr
	 #+END_SRC
   - To protect the private key from been peeked by others, ~chmod 600
     .bashrc~. After that, ~source .bashrc~ to re execute the script.

** Create a EC2 instance (OmniOS)
   - Specifiy the image ::
	 To specify the OmniOS we want, one way to find needed ami-id is:
	 #+BEGIN_SRC bash
	 ec2-describe-images -x all | grep OmniOS
	 #+END_SRC
	 For Linux
	 According to the version infomation, we know the wanted ami-id
     for OmniOS is *ami-505ce739*
   - Create a keypair for further ssh usage ::
	 #+BEGIN_SRC bash
     ec2-create-keypair omni-keypair
     #+END_SRC	

	 Then copy the output private key to create omni-keypair.pem.
	 Set the permission of this file. Only the creater can view it.
	 #+BEGIN_SRC bas
     chmod 400 omni-keypair.pem
     #+END_SRC

   - Create a Security group ::
	 Create the security group to allow only several ports can access
     it
	 #+BEGIN_SRC bash
     ec2-create-group omni-ports -d "Security Group for OmniOS"
	 ec2-authorize omni-ports -P tcp -p 22
     #+END_SRC

   - Run the instance ::
	 Lanuch the instance, use the infomation we got before(ami-id,
     keypair and security group)
  	 #+BEGIN_SRC bash
     ec2-run-instances ami-505ce739 -k omni-keypair -g omni-ports -t t1.micro
     #+END_SRC

   - Connect to the instance via SSH ::
	 Now login to the running instance with given keypair:
     #+BEGIN_SRC bash
     ssh -i omni-keypair.pem root@<Public DNS>
     #+END_SRC
	
   - Check and terminate ::
	 To check the status of instance
	 #+BEGIN_SRC bash
     ec2-describe-instance <instance id>
     #+END_SRC
     To terminate instance:
	 #+BEGIN_SRC bash
     ec2-terminate-instace <instance id>
     #+END_SRC

	 
** Show Instance info
   - display basic system information  ::
	 ~uname -a~
	 #+BEGIN_SRC bash
	 SunOS domU-12-31-39-0F-1C-BB.compute-1.internal 5.11 omnios-33fdde4 i86pc i386 i86xpv Solaris
	 #+END_SRC
   - display the partition table ::
	 Unfortunately, I didn't find fstab in Solaris. So, use this command:
	 ~format~
	 ~format> verify~
	 The output are below:
	#+BEGIN_SRC bash
	 Primary label contents:
     Volume name = <        >
     ascii name  = <DEFAULT cyl 4085 alt 2 hd 128 sec 32>
     pcyl        = 4087
     ncyl        = 4085
     acyl        =    2
     bcyl        =    0
     nhead       =  128
     nsect       =   32
     Part      Tag    Flag     Cylinders        Size            Blocks
      0       root    wm       1 - 4084        7.98GB    (4084/0/0) 16728064
      1 unassigned    wu       0               0         (0/0/0)           0
      2     backup    wu       0 - 4084        7.98GB    (4085/0/0) 16732160
      3 unassigned    wu       0               0         (0/0/0)           0
      4 unassigned    wu       0               0         (0/0/0)           0
      5 unassigned    wu       0               0         (0/0/0)           0
      6 unassigned    wu       0               0         (0/0/0)           0
      7 unassigned    wu       0               0         (0/0/0)           0
      8       boot    wu       0 -    0        2.00MB    (1/0/0)        4096
      9 unassigned    wu       0               0         (0/0/0)           0
	 #+END_SRC
   - display the currently mounted filesystems ::
	 ~mount~
	#+BEGIN_SRC bash
	 / on syspool/ROOT/omnios-r151004 read/write/setuid/devices/dev=1850002 on Wed Dec 31 19:00:00 1969
	 /devices on /devices read/write/setuid/devices/dev=8240000 on Fri Jan 24 00:14:59 2014
	 /dev on /dev read/write/setuid/devices/dev=8280000 on Fri Jan 24 00:14:59 2014
	 /system/contract on ctfs read/write/setuid/devices/dev=8340001 on Fri Jan 24 00:15:02 2014
	 /proc on proc read/write/setuid/devices/dev=82c0000 on Fri Jan 24 00:15:02 2014
	 /etc/mnttab on mnttab read/write/setuid/devices/dev=8380001 on Fri Jan 24 00:15:02 2014
	 /etc/svc/volatile on swap read/write/setuid/devices/xattr/dev=83c0001 on Fri Jan 24 00:15:02 2014
	 /system/object on objfs read/write/setuid/devices/dev=8400001 on Fri Jan 24 00:15:02 2014
	 /etc/dfs/sharetab on sharefs read/write/setuid/devices/dev=8440001 on Fri Jan 24 00:15:02 2014
	 /lib/libc.so.1 on /usr/lib/libc/libc_hwcap3.so.1 read/write/setuid/devices/dev=1850002 on Fri Jan 24 00:15:44 2014
	 /dev/fd on fd read/write/setuid/devices/dev=8540001 on Fri Jan 24 00:15:48 2014
	 /tmp on swap read/write/setuid/devices/xattr/dev=83c0002 on Fri Jan 24 00:15:49 2014
	 /var/run on swap read/write/setuid/devices/xattr/dev=83c0003 on Fri Jan 24 00:15:49 2014
	 /syspool on syspool read/write/setuid/devices/nonbmand/exec/xattr/atime/dev=1850007 on Fri Jan 24 00:15:58 2014
	 #+END_SRC
   - display available disk space ::
	 use ~df~ command, with human readable format
	 ~df -h~
	 #+BEGIN_SRC bash
	 Filesystem                      Size  Used Avail Use% Mounted on
	 syspool/ROOT/omnios-r151004     7.9G  777M  7.1G  10% /
	 swap                            215M  288K  215M   1% /etc/svc/volatile
	 /usr/lib/libc/libc_hwcap3.so.1  7.9G  777M  7.1G  10% /lib/libc.so.1
	 swap                            215M     0  215M   0% /tmp
	 swap                            215M   36K  215M   1% /var/run
	 syspool                         7.1G   37K  7.1G   1% /syspool
	 #+END_SRC
	 
** Commands to run
   - ~uname -a~ ::
  	 #+BEGIN_SRC bash
 	 SunOS domU-12-31-39-0F-1C-BB.compute-1.internal 5.11 omnios-33fdde4 i86pc i386 i86xpv Solaris
	 #+END_SRC
   - ~whoami~ ::
	 #+BEGIN_SRC bash
	 root
	 #+END_SRC
   - ~date~ ::
	 #+BEGIN_SRC bash
	 January 24, 2014 12:58:47 AM EST
	 #+END_SRC
   - ~w~ ::
   	 #+BEGIN_SRC bash
	 12:59am  up 44 min(s),  1 user,  load average: 0.00, 0.00, 0.00
	 User     tty           login@  idle   JCPU   PCPU  what
	 root     pts/1        12:30am                      w
	 #+END_SRC
   - ~ifconfig -a~ ::
	 #+BEGIN_SRC bash
	 lo0: flags=2001000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv4,VIRTUAL> mtu 8232 index 1
     inet 127.0.0.1 netmask ff000000 
	 xnf0: flags=1004843<UP,BROADCAST,RUNNING,MULTICAST,DHCP,IPv4> mtu 1500 index 2
     inet 172.31.43.110 netmask fffff000 broadcast 172.31.47.255
     ether 12:a7:95:b4:79:71 
	 lo0: flags=2002000849<UP,LOOPBACK,RUNNING,MULTICAST,IPv6,VIRTUAL> mtu 8252 index 1
     inet6 ::1/128 
	 xnf0: flags=20002000840<RUNNING,MULTICAST,IPv6> mtu 1500 index 2
     inet6 ::/0 
     ether 12:a7:95:b4:79:71 
	 #+END_SRC 
   - ~netstat -na~ ::
	 #+BEGIN_SRC bash
	 UDP: IPv4
	 Local Address        Remote Address      State
	 -------------------- -------------------- ----------
     *.68                                Idle
     *.546                               Idle
	 172.31.43.110.68                          Idle
     *.111                               Idle
     *.*                                 Unbound
     *.34664                             Idle
     *.111                               Idle
     *.*                                 Unbound
     *.62730                             Idle
     *.*                                 Unbound
	 
	 UDP: IPv6
	 Local Address                     Remote Address                   State      If
	 --------------------------------- --------------------------------- ---------- -----
     *.546                                                         Idle       
     *.111                                                         Idle       
     *.*                                                           Unbound    
     *.34664                                                       Idle       
     *.*                                                           Unbound    
	 
	 TCP: IPv4
	 Local Address        Remote Address    Swind Send-Q Rwind Recv-Q    State
	 -------------------- -------------------- ----- ------ ----- ------ -----------
	 127.0.0.1.4999             *.*                0      0 128000      0 LISTEN
     *.111                *.*                0      0 128000      0 LISTEN
     *.*                  *.*                0      0 128000      0 IDLE
     *.111                *.*                0      0 128000      0 LISTEN
     *.*                  *.*                0      0 128000      0 IDLE
     *.50196              *.*                0      0 128000      0 LISTEN
     *.44266              *.*                0      0 128000      0 LISTEN
     *.22                 *.*                0      0 128000      0 LISTEN
	 172.31.43.110.22     72.76.187.129.56666  131040      0 128872      0 ESTABLISHED
	 
	 TCP: IPv6
	 Local Address                     Remote Address                 Swind Send-Q Rwind Recv-Q   State      If
	 --------------------------------- --------------------------------- ----- ------ ----- ------ ----------- -----
     *.111                             *.*                             0      0 128000      0 LISTEN      
     *.*                               *.*                             0      0 128000      0 IDLE        
     *.44266                           *.*                             0      0 128000      0 LISTEN      
     *.22                              *.*                             0      0 128000      0 LISTEN      
	 
	 Active UNIX domain sockets
	 Address  Type          Vnode     Conn  Local Addr      Remote Addr
	 ffffff0098279b38 stream-ord ffffff0098096900 0000000 /tmp/ssh-XX4maWeb/agent.550                
	 ffffff0096613020 dgram      ffffff009709e980 0000000 /var/run/in.ndpd_mib                
	 ffffff00966133d0 stream-ord ffffff009709eb80 0000000 /var/run/in.ndpd_ipadm                
	 ffffff0096613780 stream-ord ffffff009707ca80 0000000 /var/run/.inetd.uds                
	 ffffff0096613b30 stream-ord 0000000 0000000 /var/run/hald/dbus-AkvYKxbIUb                
	 ffffff009651d018 stream-ord 0000000 0000000 /var/run/dbus/system_bus_socket                
	 ffffff009651d3c8 stream-ord 0000000 ffffff0096257d00                /var/run/dbus/system_bus_socket 
	 ffffff009651d778 stream-ord 0000000 ffffff0096413700                /var/run/hald/dbus-AkvYKxbIUb 
	 ffffff009651db28 stream-ord 0000000 0000000 /var/run/hald/dbus-AkvYKxbIUb                
	 ffffff009640c010 stream-ord 0000000 ffffff0096413700                /var/run/hald/dbus-AkvYKxbIUb 
	 ffffff009640c3c0 stream-ord 0000000 0000000 /var/run/hald/dbus-chK7PX7wXr                
	 ffffff009640c770 stream-ord 0000000 ffffff009637b000                /var/run/hald/dbus-chK7PX7wXr 
	 ffffff009640cb20 stream-ord ffffff009637b000 0000000 /var/run/hald/dbus-chK7PX7wXr                
	 ffffff0095461008 stream-ord 0000000 0000000                               
	 ffffff00954613b8 stream-ord 0000000 0000000                               
	 ffffff0095461768 stream-ord ffffff0096413700 0000000 /var/run/hald/dbus-AkvYKxbIUb                
	 ffffff0095461b18 stream-ord ffffff0096257d00 0000000 /var/run/dbus/system_bus_socket 
	 #+END_SRC

** Create another instance (Linux)
   The process of create a linux instance almost the same. The only
   difference is choose a Linux ami-id, in this case, I
   choose *ami-ab36fbc2*, ubuntu-lucid-10.04, 32 bit. Again, login
   with =SSH=, if is for long term usage, we can add host to =~/.ssh/config=.
   
** Show Instance info
   - display basic system information ::
	 ~uname -a~
	 #+BEGIN_SRC bash
	 Linux ip-172-31-39-169 2.6.32-318-ec2 #38-Ubuntu SMP Thu Sep 1 17:54:33 UTC 2011 i686 GNU/Linux
	 #+END_SRC	
   - display the partition table ::
	 ~less /etc/fstab~
     #+BEGIN_SRC bash
	 # /etc/fstab: static file system information.
     # <file system>                                 <mount point>   <type>  <options>       <dump>  <pass>
     proc                                            /proc           proc    nodev,noexec,nosuid 0       0
     LABEL=cloudimg-rootfs                                       /               ext3    defaults        0       0
     /dev/sda2	/mnt	auto	defaults,nobootwait,comment=cloudconfig	0	0
	 #+END_SRC	
   - display the currently mounted filesystems ::
     ~mount | column -t~
 	 #+BEGIN_SRC bash
     /dev/sda1  on  /                     type  ext3        (rw)
     proc       on  /proc                 type  proc        (rw,noexec,nosuid,nodev)
     none       on  /sys                  type  sysfs       (rw,noexec,nosuid,nodev)
     none       on  /sys/kernel/debug     type  debugfs     (rw)
     none       on  /sys/kernel/security  type  securityfs  (rw)
     none       on  /dev                  type  devtmpfs    (rw,mode=0755)
     none       on  /dev/pts              type  devpts      (rw,noexec,nosuid,gid=5,mode=0620)
     none       on  /dev/shm              type  tmpfs       (rw,nosuid,nodev)
     none       on  /var/run              type  tmpfs       (rw,nosuid,mode=0755)
     none       on  /var/lock             type  tmpfs       (rw,noexec,nosuid,nodev)
     none       on  /lib/init/rw          type  tmpfs       (rw,nosuid,mode=0755)
	 #+END_SRC 
   - display available disk space :: 
      ~df -h~
	 #+BEGIN_SRC bash
	 Filesystem                      Size  Used Avail Use% Mounted on
	 syspool/ROOT/omnios-r151004     7.9G  777M  7.1G  10% /
	 swap                            215M  288K  215M   1% /etc/svc/volatile
	 /usr/lib/libc/libc_hwcap3.so.1  7.9G  777M  7.1G  10% /lib/libc.so.1
	 swap                            215M     0  215M   0% /tmp
	 swap                            215M   36K  215M   1% /var/run
	 syspool                         7.1G   37K  7.1G   1% /syspool
	 #+END_SRC
** Commands to run
   - ~uname -a~ ::
  	 #+BEGIN_SRC bash
     Linux ip-172-31-39-169 2.6.32-318-ec2 #38-Ubuntu SMP Thu Sep 1 17:54:33 UTC 2011 i686 GNU/Linux
	 #+END_SRC
   - ~whoami~ ::
	 #+BEGIN_SRC bash
	 ubuntu
	 #+END_SRC
   - ~date~ ::
	 #+BEGIN_SRC bash
	 Fri Jan 24 17:53:31 UTC 2014
	 #+END_SRC
   - ~w~ ::
   	 #+BEGIN_SRC bash
	 17:54:05 up 14 min,  1 user,  load average: 0.00, 0.00, 0.00
     USER     TTY      FROM              LOGIN@   IDLE   JCPU   PCPU WHAT
     ubuntu   pts/0    pool-72-76-187-1 17:51    0.00s  0.19s  0.00s w
	 #+END_SRC
   - ~ifconfig -a~ ::
	 #+BEGIN_SRC bash
     dummy0    Link encap:Ethernet  HWaddr da:ba:91:38:43:0c  
               BROADCAST NOARP  MTU:1500  Metric:1
               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
               collisions:0 txqueuelen:0 
               RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
      
     eql       Link encap:Serial Line IP  
               MASTER  MTU:576  Metric:1
               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
               collisions:0 txqueuelen:5 
               RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
      
     eth0      Link encap:Ethernet  HWaddr 12:61:b9:e0:8c:6b  
               inet addr:172.31.39.169  Bcast:172.31.47.255  Mask:255.255.240.0
               inet6 addr: fe80::1061:b9ff:fee0:8c6b/64 Scope:Link
               UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
               RX packets:704 errors:0 dropped:0 overruns:0 frame:0
               TX packets:477 errors:0 dropped:0 overruns:0 carrier:0
               collisions:0 txqueuelen:1000 
               RX bytes:77419 (77.4 KB)  TX bytes:54672 (54.6 KB)
      
     ifb0      Link encap:Ethernet  HWaddr 12:e4:cc:79:09:7b  
               BROADCAST NOARP  MTU:1500  Metric:1
               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
               collisions:0 txqueuelen:32 
               RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
      
     ifb1      Link encap:Ethernet  HWaddr a2:40:2b:de:98:06  
               BROADCAST NOARP  MTU:1500  Metric:1
               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
               collisions:0 txqueuelen:32 
               RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
      
     lo        Link encap:Local Loopback  
               inet addr:127.0.0.1  Mask:255.0.0.0
               inet6 addr: ::1/128 Scope:Host
               UP LOOPBACK RUNNING  MTU:16436  Metric:1
               RX packets:0 errors:0 dropped:0 overruns:0 frame:0
               TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
               collisions:0 txqueuelen:0 
               RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
	 #+END_SRC 
   - ~netstat -na~ ::
	 #+BEGIN_SRC bash
     Active Internet connections (servers and established)
     Proto Recv-Q Send-Q Local Address           Foreign Address         State      
     tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
     tcp        0     32 172.31.39.169:22        72.76.187.129:60188     ESTABLISHED
     tcp6       0      0 :::22                   :::*                    LISTEN     
     udp        0      0 0.0.0.0:68              0.0.0.0:*                          
     Active UNIX domain sockets (servers and established)
     Proto RefCnt Flags       Type       State         I-Node   Path
     unix  2      [ ACC ]     STREAM     LISTENING     6700     /tmp/ssh-KyDVxrS882/agent.882
     unix  4      [ ]         DGRAM                    5651     /dev/log
     unix  2      [ ACC ]     STREAM     LISTENING     3541     @/com/ubuntu/upstart
     unix  2      [ ]         DGRAM                    3640     @/org/kernel/udev/udevd
     unix  2      [ ACC ]     STREAM     LISTENING     5599     /var/run/dbus/system_bus_socket
     unix  3      [ ]         STREAM     CONNECTED     6697     
     unix  3      [ ]         STREAM     CONNECTED     6696     
     unix  3      [ ]         STREAM     CONNECTED     6558     /var/run/dbus/system_bus_socket
     unix  3      [ ]         STREAM     CONNECTED     6557     
     unix  2      [ ]         DGRAM                    6556     
     unix  3      [ ]         STREAM     CONNECTED     6009     /var/run/dbus/system_bus_socket
     unix  3      [ ]         STREAM     CONNECTED     6008     
     unix  3      [ ]         STREAM     CONNECTED     5983     /var/run/dbus/system_bus_socket
     unix  3      [ ]         STREAM     CONNECTED     5982     
     unix  2      [ ]         DGRAM                    5724     
     unix  3      [ ]         STREAM     CONNECTED     5629     /var/run/dbus/system_bus_socket
     unix  3      [ ]         STREAM     CONNECTED     5628     
     unix  3      [ ]         STREAM     CONNECTED     5612     
     unix  3      [ ]         STREAM     CONNECTED     5611     
     unix  3      [ ]         DGRAM                    3669     
     unix  3      [ ]         DGRAM                    3668     
     unix  3      [ ]         STREAM     CONNECTED     3623     @/com/ubuntu/upstart
     unix  3      [ ]         STREAM     CONNECTED     3622 
	 #+END_SRC

** Reference
   - [[http://paulstamatiou.com/how-to-getting-started-with-amazon-ec2/][How To: Getting Started with Amazon EC2]]
   - [[http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/SettingUp_CommandLine.html#tools-introduction][Setting Up the Amazon EC2 Command Line Interface Tools on Linux/UNIX and Mac OS X]]
   - [[http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/command-reference.html][CLI Tools Reference]]
   - [[http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ec2-cli-launch-instance.html][EC2 CLI Lanuch Instance]]
   - [[http://www.cs.stevens.edu/~hshen4/CS615/HW1/HW1-hshen4.html]]


